int client();
static int update();
static int load_screen();
static int return_to_main_page();
static int log_ip();
void proceess_option(int option);
static int option_pressed0();
static int option_pressed1();
static int option_pressed2();
static int option_pressed3();
char * extract_song(char * raw_song);
void do_stuff();
void scramble_order();
